export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const RECEIVE_LOGIN = "RECEIVE_LOGIN";
export const ADD_PHONE = "ADD_PHONE";
export const ADD_FIRST_NAME = "ADD_FIRST_NAME";
export const ADD_LAST_NAME = "ADD_LAST_NAME";

export const REQUEST_ADD_PRODUCT = "REQUEST_ADD_PRODUCT";
export const ADD_BASKET_PRODUCT = "ADD_BASKET_PRODUCT";
export const LOAD_BASKET_INFO = "LOAD_BASKET_INFO";
export const LOAD_BASKET_PRODUCTS = "LOAD_BASKET_PRODUCTS";
export const CLEAR_BASKET_AFTER_ORDER = "CLEAR_BASKET_AFTER_ORDER";

export const ADD_ADDRESS_ID = "ADD_ADDRESS_ID"

export const REQUEST_API_PRODUCTS = "REQUEST_API_PRODUCTS";
export const RECEIVE_API_PRODUCTS = "RECEIVE_API_PRODUCTS";
export const ADD_PRODUCT_TO_BASKET = "ADD_PRODUCT_TO_BASKET"
